from pathlib import Path

from dotenv import load_dotenv
from fastapi import Response
from mlflow.genai.agent_server import AgentServer, setup_mlflow_git_based_version_tracking

# Load env vars from .env before importing the agent for proper auth
load_dotenv(dotenv_path=Path(__file__).parent.parent / ".env", override=True)

# Need to import the agent to register the functions with the server
import agent_server.agent  # noqa: E402
from agent_server.visualization import get_cached_chart

agent_server = AgentServer("ResponsesAgent", enable_chat_proxy=True)

# Define the app as a module level variable to enable multiple workers
app = agent_server.app  # noqa: F841
setup_mlflow_git_based_version_tracking()


# The frontend proxies exactly one backend path -- POST /invocations -- to
# this server (see server/src/index.ts in databricks/app-templates'
# e2e-chatbot-app-next, which the local dev "start-app" command clones). It's
# the only backend route reachable from the browser, so chart images
# generated by the `generate_chart` tool (agent_server/visualization.py) are
# served back through a GET on that same path rather than a dedicated route.
@app.get("/invocations")
def get_chart(chart_id: str):
    png_bytes = get_cached_chart(chart_id)
    if png_bytes is None:
        return Response(status_code=404)
    return Response(content=png_bytes, media_type="image/png")


def main():
    agent_server.run(app_import_string="agent_server.start_server:app")
